import './globals.css'

import { Container, CssBaseline, ThemeProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ComponentWithChildren } from '@/types/ComponentWithChildren'

import darkTheme from './dark.theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shopping app',
  description: 'Generated by me'
}

export default function RootLayout({ children }: ComponentWithChildren) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={darkTheme}>
            <CssBaseline>
              <Container>{children}</Container>
            </CssBaseline>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
