version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/shop?schema=public
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - ./server/node_modules:/usr/src/app/node_modules
      - ./server/.env:/usr/src/app/.env

  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile.dev
    container_name: web-ui
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./web-ui:/usr/src/app
      - ./web-ui/node_modules:/usr/src/app/node_modules

volumes:
  db-data:
