# Use the official Node.js image.
FROM node:22.4.1

# Install pnpm
RUN npm install -g pnpm

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY .env ./

# Install all dependencies.
RUN pnpm install

# Copy local code to the container image.
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Run the development server with nodemon for hot reloading
CMD ["pnpm", "run", "start:dev"]
